[package]
name = "smelter-worker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-stack = "0.4.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"

[features]
default = ["spawner-side", "worker-side"]
worker-side = []
# Functionality only used by the Smelter job spawners and the job manager.
spawner-side = []
