[package]
name = "job-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.3"
async-trait = "0.1.68"
error-stack = { version = "0.3.1", features = ["serde", "eyre"] }
eyre = "0.6.8"
flume = { version = "0.10.14", optional = true }
futures = "0.3.28"
serde = { version = "1.0.164", features = ["derive"] }
tempfile = "3.6.0"
thiserror = "1.0.40"
time = { version = "0.3.23", features = ["serde"] }
tokio = { version = "1.29.1", features = ["full"] }
tracing = "0.1.37"

[features]
default = ["inprocess"]
inprocess = ["flume"]

[dev-dependencies]
once_cell = "1.18.0"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tracing-tree = "0.2.4"
